swiftmailer:
    # ne pas oublier d'activer "Accès moins sécurisé des applications"
    # via le compte gmail utilisé ici (https://myaccount.google.com/security)
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }
    transport:        gmail
    username:         '%mailer_user%'
    password:         '%mailer_password%'
#    username:         noreply@infoway.fr
#    password:         Annesivy1974
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false