vich_uploader:
    db_driver: orm

    mappings:
        media_file:
            uri_prefix: /images/media
            upload_destination: '%kernel.project_dir%/public/images/media'
            namer: Vich\UploaderBundle\Naming\UniqidNamer # how uploaded file will be rename (If no namer is configured for a mapping, the bundle will simply use the name of the file that was uploaded)

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
