<?php

namespace App\Repository\Customer;

use App\Entity\Customer\CriterionsList;
use Doctrine\Bundle\DoctrineBundle\DoctrineBundle;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\SessionInterface;


class CustomerRepository extends ServiceEntityRepository
{

    public function __construct(EntityManagerInterface $doctrine, ManagerRegistry $registry , ?string $entityClass )
    {
        dd($doctrine);
        parent::__construct($registry, $entityClass);
        dd($this->_em);
       // $this->_em = $registry->getManager();


    }

    public function setEntityManager(ObjectManager $entityManager): self
    {
        $this->_em = $entityManager;
        return $this;
    }


    public function __call($method, $arguments)
    {
         parent::__call($method, $arguments); // TODO: Change the autogenerated stub

    }
}